export const conceptMaps = {
  workExperience: [
    'experience',
    'work',
    'job',
    'career',
    'company',
    'employment',
    'position',
    'role',
    'profession',
    'occupation',
    'rotaready',
    'history',
    'worked',
    'professional',
    'resume',
    'cv',
    'employed',
    'hired',
    'gig',
  ],

  projects: [
    'project',
    'portfolio',
    'build',
    'develop',
    'create',
    'app',
    'application',
    'website',
    'web app',
    'coding',
    'built',
    'created',
    'developed',
    'made',
    'program',
    'startup',
    'product',
    'solution',
    'platform',
    'system',
  ],

  skills: [
    'skill',
    'technology',
    'tech stack',
    'framework',
    'programming language',
    'react',
    'javascript',
    'typescript',
    'tool',
    'library',
    'proficient',
    'expertise',
    'competency',
    'ability',
    'capable',
    'stack',
    'tech',
    'coding',
    'development',
    'web',
    'frontend',
    'backend',
    'fullstack',
  ],

  education: [
    'education',
    'degree',
    'university',
    'college',
    'study',
    'school',
    'academic',
    'student',
    'graduate',
    'graduation',
    'class',
    'course',
    'program',
    'major',
    'learn',
    'certificate',
    'diploma',
    'studied',
    'qualification',
    'training',
  ],

  interests: [
    'interest',
    'hobby',
    'hobbies',
    'passion',
    'personal',
    'free time',
    'outside of work',
    'fun',
    'leisure',
    'scuba',
    'travel',
    'diving',
    'enjoy',
    'like',
    'love',
    'pastime',
    'recreation',
    'entertainment',
    'activity',
    'downtime',
    'weekend',
    'relaxation',
    'adventure',
  ],

  languages: [
    'languages',
    'speak',
    'speaking',
    'spanish',
    'portuguese',
    'bilingual',
    'multilingual',
    'fluent',
    'native',
    'conversation',
    'talk',
    'verbal',
    'dialect',
    'tongue',
  ],

  certifications: [
    'certification',
    'certificate',
    'license',
    'qualified',
    'credential',
    'accreditation',
    'permit',
    'tefl',
    'real estate',
    'diver',
    'scuba',
    'qualified',
    'authorized',
    'certified',
    'trained',
    'recognized',
  ],

  about: [
    'about',
    'who',
    'introduce',
    'background',
    'aaron',
    'tell me about',
    'bio',
    'person',
    'profile',
    'overview',
    'summary',
    'intro',
    'identity',
    'personal info',
    'description',
    'introduction',
  ],
};
